name: OpenToFu Plan and Apply on Main Branch Push

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: 'tofu Plan'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: modules/
    env:
      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_PRIVATE_KEY: ${{ secrets.SNOWFLAKE_PRIVATE_KEY }}
      SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup OpenTofu
      uses: opentofu/setup-opentofu@v1

    - name: OpenTofu Initialize
      run: tofu plan -no-color

    - name: OpenTofu Validate
      run: tofu validate -no-color

    - name: OpenTofu Plan
      run: tofu plan -no-color

    - name: OpenTofu Apply
      run: tofu apply -no-color-auto-approve